name: "Hello World"

on:
  push:
    branches:
      - master
      - production

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"
